machine:
  python:
    version: 3.4.3
  node:
    version: 0.12.2
  environment:
    DJANGO_SETTINGS_MODULES: edwin.settings
    DJANGO_CONFIGURATION: Test
    DATABASE_URL: postgres://ubuntu:@127.0.0.1:5432/circle_test

dependencies:
  override:
    - npm install
    - pip install -r requirements.txt

database:
  override:
    - python manage.py migrate

test:
  override:
    - python manage.py test
    - npm test
    - python manage.py collectstatic --noinput
