language: python
python: 3.4
install:
  - pip install -r requirements.txt
  - npm --python=$(which python2.7) install
  - DJANGO_SETTINGS_MODULE=edwin.settings DJANGO_CONFIGURATION=Test ./manage.py collectstatic --noinput
script:
  - DJANGO_SETTINGS_MODULE=edwin.settings DJANGO_CONFIGURATION=Test ./manage.py test
  - npm test
branches:
  only:
    - master
