language: python
python: 3.4
env:
  - DJANGO_SETTINGS_MODULE="edwin.settings" DJANGO_CONFIGURATION="Test"
install:
  - pip install -r requirements.txt
  - npm --python=$(which python2.7) install
script:
  - ./manage.py test
  - npm test
